# Generated by Django 6.0.4 on 2026-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('target_joint', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('min_angle', models.FloatField()),
                ('max_angle', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
