# Generated by Django 6.0.4 on 2026-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0004_doctorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rehabplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
